"""Generate embedded_assets.inc: patch files as C byte arrays.

Run from the repository root (tools/package.bat does this)."""
import sys

def emit(var, path, out):
    data = open(path, 'rb').read()
    out.write("static const unsigned char %s[] = {" % var)
    for i, b in enumerate(data):
        if i % 16 == 0:
            out.write("\n    ")
        out.write("0x%02x," % b)
    out.write("\n};\n")
    out.write("static const unsigned int %s_size = %d;\n\n"
              % (var, len(data)))

with open(sys.argv[1], 'w') as out:
    out.write("/* generated by gen_assets.py - do not edit */\n\n")
    emit('g_dinput', r'src\proxy\dinput.dll', out)
    emit('g_ini', r'src\proxy\WindowSize.ini', out)
    emit('g_readme', r'README.md', out)
