/*
 * Sengoku Rance multi-resolution patch installer.
 *
 * A single self-contained exe: the patch files are embedded as byte
 * arrays (embedded_assets.inc, generated by gen_assets.py). Locates
 * the game folder via Steam's libraryfolders.vdf (app 3867170),
 * falls back to a folder-browse dialog, then writes dinput.dll and
 * MultiRes.ini next to Rance7.exe.
 */
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <shlobj.h>

#define APPID "3867170"
#define GAME_EXE "Rance7.exe"

/* Tiny CRT-free string helpers (built with -nodefaultlib). */
static char *find_str(char *h, const char *n)
{
    for (; *h; h++) {
        const char *a = h, *b = n;
        while (*b && *a == *b) { a++; b++; }
        if (!*b)
            return h;
    }
    return NULL;
}

static char *find_chr(char *h, int c)
{
    for (; *h && *h != c; h++)
        ;
    return *h == c ? h : NULL;
}

static void zero(void *p, DWORD n)
{
    char *c = p;
    while (n--)
        *c++ = 0;
}

static void copy_mem(void *d, const void *s, DWORD n)
{
    char *a = d;
    const char *b = s;
    while (n--)
        *a++ = *b++;
}

/* generated at build time: unsigned char g_dinput[], g_ini[],
   g_readme[] plus matching sizes */
#include "embedded_assets.inc"

struct file_entry {
    const char *name;
    const unsigned char *data;
    unsigned int size;
    int optional_overwrite; /* keep an existing user-modified file */
};

static const struct file_entry FILES[] = {
    { "dinput.dll", g_dinput, g_dinput_size, 0 },
    { "MultiRes.ini", g_ini, g_ini_size, 1 },
    { "README_patch.txt", g_readme, g_readme_size, 0 },
};

/* --- Steam library detection -------------------------------------------- */

/* Parse "path" values out of libraryfolders.vdf into out paths. */
static int parse_vdf_paths(const char *text, char out[][MAX_PATH], int max)
{
    int n = 0;
    const char *p = text;
    while ((p = find_str((char *)p, "\"path\"")) != NULL && n < max) {
        const char *v = find_chr((char *)p + 6, '"');
        const char *e;
        char *w;
        if (!v)
            break;
        v++;
        e = find_chr((char *)v, '"');
        if (!e)
            break;
        w = out[n];
        /* vdf escapes backslashes: "C:\\foo" -> C:\foo */
        while (v < e && w - out[n] < MAX_PATH - 1) {
            if (*v == '\\' && v + 1 < e)
                v++;
            *w++ = *v++;
        }
        *w = 0;
        n++;
        p = e;
    }
    return n;
}

static int read_all(const char *path, char *buf, DWORD cap)
{
    HANDLE f = CreateFileA(path, GENERIC_READ, FILE_SHARE_READ, NULL,
                           OPEN_EXISTING, 0, NULL);
    DWORD got = 0;
    BOOL ok;
    if (f == INVALID_HANDLE_VALUE)
        return 0;
    ok = ReadFile(f, buf, cap - 1, &got, NULL);
    CloseHandle(f);
    buf[ok ? got : 0] = 0;
    return ok ? (int)got : 0;
}

static int file_exists(const char *dir, const char *name)
{
    char p[MAX_PATH];
    wsprintfA(p, "%s\\%s", dir, name);
    return GetFileAttributesA(p) != INVALID_FILE_ATTRIBUTES;
}

/* Read installdir out of an appmanifest_*.acf. */
static int acf_installdir(const char *acf, char *out, DWORD cap)
{
    char buf[4096];
    const char *p, *e;
    if (!read_all(acf, buf, sizeof(buf)))
        return 0;
    p = find_str(buf, "\"installdir\"");
    if (!p)
        return 0;
    p = find_chr((char *)p + 11, '"');
    if (!p)
        return 0;
    p++;
    while (*p == ' ' || *p == '\t')
        p++;
    if (*p == '"')
        p++;
    e = find_chr((char *)p, '"');
    if (!e || (DWORD)(e - p) >= cap)
        return 0;
    copy_mem(out, p, e - p);
    out[e - p] = 0;
    return 1;
}

/* Check "<steamapps>\appmanifest_<appid>.acf" and, if present, whether
   "<steamapps>\common\<installdir>\Rance7.exe" exists. */
static int check_library(const char *steamapps, char *out, DWORD cap)
{
    char acf[MAX_PATH], inst[MAX_PATH], dir[MAX_PATH];
    wsprintfA(acf, "%s\\appmanifest_" APPID ".acf", steamapps);
    if (!acf_installdir(acf, inst, sizeof(inst)))
        return 0;
    wsprintfA(dir, "%s\\common\\%s", steamapps, inst);
    if (!file_exists(dir, GAME_EXE))
        return 0;
    lstrcpynA(out, dir, cap);
    return 1;
}

/* Find the game's install dir by scanning every fixed drive's
   steamapps folders (main Steam library plus any "SteamLibrary"
   secondary libraries) and each library's libraryfolders.vdf for
   additional registered libraries. Registry-free: the Valve key is
   unreliable on some systems. */
static int detect_game_dir(char *out, DWORD cap)
{
    static const char *roots[] = {
        "%c:\\SteamLibrary\\steamapps",
        "%c:\\Steam\\steamapps",
        "%c:\\Program Files (x86)\\Steam\\steamapps",
        "%c:\\Program Files\\Steam\\steamapps",
        "%c:\\Games\\SteamLibrary\\steamapps",
    };
    char (*libs)[MAX_PATH];
    char *text;
    DWORD drives = GetLogicalDrives(), bit, cnt = 0;
    int i, found = 0;
    UINT r;

    libs = HeapAlloc(GetProcessHeap(), 0, 96 * MAX_PATH);
    text = HeapAlloc(GetProcessHeap(), 0, 1 << 20);
    for (bit = 0; bit < 26 && cnt < 90; bit++) {
        char sa[MAX_PATH];
        if (!((drives >> bit) & 1))
            continue;
        sa[0] = 'A' + (char)bit;
        sa[1] = ':';
        sa[2] = '\\';
        sa[3] = 0;
        if (GetDriveTypeA(sa) != DRIVE_FIXED)
            continue;
        for (r = 0; r < sizeof(roots) / sizeof(roots[0]); r++) {
            wsprintfA(sa, roots[r], 'A' + (char)bit);
            if (GetFileAttributesA(sa) != INVALID_FILE_ATTRIBUTES &&
                cnt < 90)
                lstrcpyA(libs[cnt++], sa);
        }
    }
    /* Parse each found steamapps dir's libraryfolders.vdf for extra
       registered libraries (the vdf sits next to it). */
    for (i = 0; i < (int)cnt; i++) {
        char vdf[MAX_PATH];
        int n;
        wsprintfA(vdf, "%s\\libraryfolders.vdf", libs[i]);
        n = read_all(vdf, text, 1 << 20);
        if (n) {
            char extra[16][MAX_PATH];
            int e = parse_vdf_paths(text, extra, 16), k;
            for (k = 0; k < e && cnt < 90; k++) {
                char sa[MAX_PATH];
                wsprintfA(sa, "%s\\steamapps", extra[k]);
                if (GetFileAttributesA(sa) != INVALID_FILE_ATTRIBUTES)
                    lstrcpyA(libs[cnt++], sa);
            }
        }
    }
    for (i = 0; i < (int)cnt && !found; i++)
        found = check_library(libs[i], out, cap);
    HeapFree(GetProcessHeap(), 0, text);
    HeapFree(GetProcessHeap(), 0, libs);
    return found;
}

/* --- folder picker ------------------------------------------------------- */

/* UI text uses the wide APIs: the source file is UTF-8 and the A
   functions would decode the literals as the system ANSI codepage,
   producing mojibake. */
static void to_wide(const char *src, WCHAR *dst, DWORD cap)
{
    if (!MultiByteToWideChar(CP_ACP, 0, src, -1, dst, cap))
        dst[0] = 0;
}

static int CALLBACK browse_cb(HWND hwnd, UINT msg, LPARAM lp, LPARAM data)
{
    (void)lp;
    if (msg == BFFM_INITIALIZED)
        SendMessageA(hwnd, BFFM_SETSELECTIONA, TRUE, data);
    return 0;
}

static int browse_dir(char *out, DWORD cap)
{
    BROWSEINFOW bi;
    LPITEMIDLIST pidl;
    zero(&bi, sizeof(bi));
    bi.lpszTitle =
        L"Select the game folder containing Rance7.exe / "
        L"Rance7.exe があるフォルダを選択してください";
    bi.ulFlags = BIF_RETURNONLYFSDIRS | BIF_NEWDIALOGSTYLE;
    bi.lpfn = browse_cb;
    bi.lParam = (LPARAM)out;
    CoInitialize(NULL);
    pidl = SHBrowseForFolderW(&bi);
    if (pidl && SHGetPathFromIDListA(pidl, out)) {
        CoTaskMemFree(pidl);
        CoUninitialize();
        return 1;
    }
    CoUninitialize();
    (void)cap;
    return 0;
}

/* --- install ------------------------------------------------------------- */

static int write_file(const char *dir, const struct file_entry *fe)
{
    char p[MAX_PATH];
    HANDLE f;
    DWORD w;
    wsprintfA(p, "%s\\%s", dir, fe->name);
    f = CreateFileA(p, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS,
                    FILE_ATTRIBUTE_NORMAL, NULL);
    if (f == INVALID_HANDLE_VALUE)
        return 0;
    WriteFile(f, fe->data, fe->size, &w, NULL);
    CloseHandle(f);
    return w == fe->size;
}

int mainCRTStartup(void)
{
    char dir[MAX_PATH], p[MAX_PATH];
    WCHAR msg[1024], wdir[MAX_PATH];
    DWORD i;
    int detected;

    dir[0] = 0;
    detected = detect_game_dir(dir, sizeof(dir));
    if (detected) {
        to_wide(dir, wdir, MAX_PATH);
        wsprintfW(msg,
                  L"Game found:\n%s\n\nInstall the patch to this "
                  L"folder?\n\nこのフォルダにパッチを適用しますか?",
                  wdir);
        if (MessageBoxW(NULL, msg, L"Sengoku Rance Multi-Res Patch",
                        MB_YESNO | MB_ICONQUESTION) != IDYES)
            dir[0] = 0;
        else if (!file_exists(dir, GAME_EXE))
            dir[0] = 0;
    }
    while (!dir[0]) {
        dir[0] = 0;
        if (!browse_dir(dir, sizeof(dir)))
            return 0; /* cancelled */
        if (!file_exists(dir, GAME_EXE)) {
            if (MessageBoxW(NULL,
                            L"Rance7.exe was not found in the selected "
                            L"folder.\n選択したフォルダに Rance7.exe "
                            L"が見つかりません。\n\nChoose again?",
                            L"Sengoku Rance Multi-Res Patch",
                            MB_YESNO | MB_ICONWARNING) != IDYES)
                return 0;
            dir[0] = 0;
        }
    }

    /* Back up a pre-existing dinput.dll (other mod or the real
       proxy) before overwriting. */
    wsprintfA(p, "%s\\dinput.dll", dir);
    if (GetFileAttributesA(p) != INVALID_FILE_ATTRIBUTES) {
        char bak[MAX_PATH];
        wsprintfA(bak, "%s\\dinput.dll.bak", dir);
        if (GetFileAttributesA(bak) == INVALID_FILE_ATTRIBUTES)
            CopyFileA(p, bak, TRUE);
    }

    for (i = 0; i < sizeof(FILES) / sizeof(FILES[0]); i++) {
        char fp[MAX_PATH];
        wsprintfA(fp, "%s\\%s", dir, FILES[i].name);
        if (FILES[i].optional_overwrite &&
            GetFileAttributesA(fp) != INVALID_FILE_ATTRIBUTES)
            continue; /* keep the user's existing settings file */
        if (!write_file(dir, &FILES[i])) {
            WCHAR wname[64];
            to_wide(FILES[i].name, wname, 64);
            to_wide(fp, wdir, MAX_PATH);
            wsprintfW(msg, L"Failed to write %s\n%s", wname, wdir);
            MessageBoxW(NULL, msg, L"Install failed", MB_ICONERROR);
            return 1;
        }
    }

    to_wide(dir, wdir, MAX_PATH);
    wsprintfW(msg,
              L"Patch installed to:\n%s\n\n"
              L"Uninstall: delete dinput.dll and MultiRes.ini in that "
              L"folder.\n\nパッチをインストールしました。\n"
              L"アンインストール: フォルダ内の dinput.dll と "
              L"MultiRes.ini を削除してください。",
              wdir);
    MessageBoxW(NULL, msg, L"Sengoku Rance Multi-Res Patch",
                MB_ICONINFORMATION);
    return 0;
}
